package com.link.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setView(java.lang.Integer view) {
		set("view", view);
	}
	
	public java.lang.Integer getView() {
		return getInt("view");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setHits(java.lang.String hits) {
		set("hits", hits);
	}
	
	public java.lang.String getHits() {
		return getStr("hits");
	}

	public void setGood(java.lang.String good) {
		set("good", good);
	}
	
	public java.lang.String getGood() {
		return getStr("good");
	}

	public void setSorter(java.lang.Integer sorter) {
		set("sorter", sorter);
	}
	
	public java.lang.Integer getSorter() {
		return getInt("sorter");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setBold(java.lang.String bold) {
		set("bold", bold);
	}
	
	public java.lang.String getBold() {
		return getStr("bold");
	}

	public void setItalic(java.lang.String italic) {
		set("italic", italic);
	}
	
	public java.lang.String getItalic() {
		return getStr("italic");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public void setStartip(java.lang.String startip) {
		set("startip", startip);
	}
	
	public java.lang.String getStartip() {
		return getStr("startip");
	}

	public void setEndip(java.lang.String endip) {
		set("endip", endip);
	}
	
	public java.lang.String getEndip() {
		return getStr("endip");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setModifytime(java.lang.String modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.lang.String getModifytime() {
		return getStr("modifytime");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("authorId", authorId);
	}
	
	public java.lang.String getAuthorId() {
		return getStr("authorId");
	}

	public void setAuthorName(java.lang.String authorName) {
		set("authorName", authorName);
	}
	
	public java.lang.String getAuthorName() {
		return getStr("authorName");
	}

	public void setModifyAuthorName(java.lang.String modifyAuthorName) {
		set("modifyAuthorName", modifyAuthorName);
	}
	
	public java.lang.String getModifyAuthorName() {
		return getStr("modifyAuthorName");
	}

	public void setModifyAuthorId(java.lang.String modifyAuthorId) {
		set("modifyAuthorId", modifyAuthorId);
	}
	
	public java.lang.String getModifyAuthorId() {
		return getStr("modifyAuthorId");
	}

}
