package com.link.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategory<M extends BaseCategory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setParent(java.lang.String parent) {
		set("parent", parent);
	}
	
	public java.lang.String getParent() {
		return getStr("parent");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setHide(java.lang.String hide) {
		set("hide", hide);
	}
	
	public java.lang.String getHide() {
		return getStr("hide");
	}

	public void setSorter(java.lang.Integer sorter) {
		set("sorter", sorter);
	}
	
	public java.lang.Integer getSorter() {
		return getInt("sorter");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setLoaded(java.lang.String loaded) {
		set("loaded", loaded);
	}
	
	public java.lang.String getLoaded() {
		return getStr("loaded");
	}

	public void setTopicId(java.lang.String topicId) {
		set("topicId", topicId);
	}
	
	public java.lang.String getTopicId() {
		return getStr("topicId");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("authorId", authorId);
	}
	
	public java.lang.String getAuthorId() {
		return getStr("authorId");
	}

	public void setAuthorName(java.lang.String authorName) {
		set("authorName", authorName);
	}
	
	public java.lang.String getAuthorName() {
		return getStr("authorName");
	}

	public void setModifytime(java.lang.String modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.lang.String getModifytime() {
		return getStr("modifytime");
	}

	public void setModifyAuthorId(java.lang.String modifyAuthorId) {
		set("modifyAuthorId", modifyAuthorId);
	}
	
	public java.lang.String getModifyAuthorId() {
		return getStr("modifyAuthorId");
	}

	public void setModifyAuthorName(java.lang.String modifyAuthorName) {
		set("modifyAuthorName", modifyAuthorName);
	}
	
	public java.lang.String getModifyAuthorName() {
		return getStr("modifyAuthorName");
	}

}
