package com.link.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setModifytime(java.lang.String modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.lang.String getModifytime() {
		return getStr("modifytime");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("authorId", authorId);
	}
	
	public java.lang.String getAuthorId() {
		return getStr("authorId");
	}

	public void setAuthorName(java.lang.String authorName) {
		set("authorName", authorName);
	}
	
	public java.lang.String getAuthorName() {
		return getStr("authorName");
	}

	public void setModifyAuthorId(java.lang.String modifyAuthorId) {
		set("modifyAuthorId", modifyAuthorId);
	}
	
	public java.lang.String getModifyAuthorId() {
		return getStr("modifyAuthorId");
	}

	public void setModifyAuthorName(java.lang.String modifyAuthorName) {
		set("modifyAuthorName", modifyAuthorName);
	}
	
	public java.lang.String getModifyAuthorName() {
		return getStr("modifyAuthorName");
	}

}
